"""
This type stub file was generated by pyright.
"""

from typing import Self

windll = ...
class CultureInfoManager:
    _instance = ...
    def __new__(cls) -> Self:
        ...
    
    def __init__(self) -> None:
        ...
    
    def SetCulture(self, culture: str) -> None:
        ...
    
    @property
    def CurrentCulture(self) -> str:
        ...
    


CultureInfo = ...
